<?php

declare(strict_types=1);

/*
 * M1ForgeFinanceAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace M1ForgeFinanceAPIsLib\Controllers;

use CoreInterfaces\Core\Request\RequestMethod;
use M1ForgeFinanceAPIsLib\Exceptions\ApiException;

class ForexController extends BaseController
{
    /**
     * Get quotes
     *
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getQuotesForAllSymbols(): void
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/quotes');

        $this->execute($_reqBuilder);
    }

    /**
     * Symbol List
     *
     * @return string[] Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getAListOfSymbolsForWhichWeProvideRealTimeQuotes(): array
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/symbols');

        return $this->execute($_reqBuilder);
    }
}
