<?php

declare(strict_types=1);

/*
 * M1ForgeFinanceAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace M1ForgeFinanceAPIsLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const SERVER1 = 'server1';

    public const SERVER2 = 'server2';
}
